# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

In [ ]:
import os

os.chdir('/content/drive/MyDrive/numpy-100')

In [ ]:
!pip install mdutils

  Created wheel for mdutils: filename=mdutils-1.3.0-cp37-none-any.whl size=19449 sha256=6452510f750a5938a84123770b8613271e0f8086047dd17f1571af1ddbd1850a
  Stored in directory: /root/.cache/pip/wheels/af/fa/1c/7b13e92bdfc39eda5970b21a15f04f6a5158dea4e3f459854d
Successfully built mdutils


File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

import numpy as np


In [ ]:
answer(1)

import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
np.show_config() # 몰랐던 내용. 체크하자

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


In [ ]:
answer(2)

print(np.__version__)
np.show_config()


#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
null_vec = np.zeros(10)
print(null_vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
answer(3)

Z = np.zeros(10)
print(Z)


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
size_q = np.zeros((10, 10))
print("array size: ", size_q.size)
print("one element memory size: ", size_q.itemsize)
print("array memory size: ", size_q.size * size_q.itemsize) # 이런게 있는줄도 몰랐다....

array size:  100
one element memory size:  8
array memory size:  800


In [ ]:
answer(4)

Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
answer(5) # 아예 처음 보는 기능이다...

%run `python -c "import numpy; numpy.info(numpy.add)"`


#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
vect = np.zeros(10)
vect[4] = 1
print(vect)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
answer(6)

Z = np.zeros(10)
Z[4] = 1
print(Z)


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
vect = np.arange(10, 50)
print(vect)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
answer(7)

Z = np.arange(10,50)
print(Z)


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
vect = np.arange(10, 30)
print(vect)

vect = np.flip(vect) 
print(vect)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
answer(8)

Z = np.arange(50)
Z = Z[::-1]
print(Z)


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
vec = np.arange(0, 9).reshape(3, 3)
print(vec)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
answer(9)

Z = np.arange(9).reshape(3, 3)
print(Z)


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
nz = np.nonzero([1, 2, 0, 0, 4, 0])
print(nz)

# Another solution
result = np.where(np.array([1, 2, 0, 0, 4, 0]) != 0)
print(result)

(array([0, 1, 4]),)
(array([0, 1, 4]),)


In [ ]:
answer(10)

nz = np.nonzero([1,2,0,0,4,0])
print(nz)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
sol = np.eye(3)
print(sol)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
answer(11)

Z = np.eye(3)
print(Z)


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
sol = np.random.random((3, 3, 3))
print(sol)

[[[0.09313988 0.63027683 0.70270008]
  [0.97973482 0.02596657 0.67896653]
  [0.85371263 0.38309047 0.51869293]]

 [[0.49819356 0.36066103 0.62776755]
  [0.7914679  0.04906851 0.761794  ]
  [0.92064355 0.94405855 0.41745092]]

 [[0.37028903 0.78001196 0.75741601]
  [0.83724789 0.12986062 0.95538317]
  [0.06144275 0.94921173 0.68536867]]]


In [ ]:
answer(12)

Z = np.random.random((3,3,3))
print(Z)


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
sol = np.random.random((10, 10))

print("minimum value: ", np.min(sol))
print("maximum value: ", np.max(sol))

# same result

print("minimum value: ", sol.min())
print("maximum value: ", sol.max())

minimum value:  0.01788972950762202
maximum value:  0.9772964318128395
minimum value:  0.01788972950762202
maximum value:  0.9772964318128395


In [ ]:
answer(13)

Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
sol = np.random.random(30)
# same results
print(np.mean(sol))
print(sol.mean())

0.5462539290880896
0.5462539290880896


In [ ]:
answer(14)

Z = np.random.random(30)
m = Z.mean()
print(m)


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
sol = np.ones((5, 10))

sol[1:-1, 1:-1] = 0 # for문으로 열심히 짰는데, 생각보다 답안은 엄청 간단하다...
print(sol)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
answer(15)

Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
# 새로운 답안 발견! 
# 가로, 세로 +2 짜리로 만든 뒤, 안쪽으로 기존 array를 넣는 식으로도 풀 수 있다.

sol = np.ones((4, 5))
print("original array: ","\n", sol, "\n")

zero_ = np.zeros((sol.shape[0]+2, sol.shape[1]+2))
print(zero_, "\n")

zero_[1:-1, 1:-1] = sol[:, :]

print(zero_)


original array:  
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]] 

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
answer(16)

Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan) # np.nan은 값이 없는 것이기 때문에 직접 값으로 비교하는 것이 불가능.
print(np.nan is np.nan) # True, np.isnan을 사용하는 것이 더 정확
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
True
False
nan
True
False


In [ ]:
answer(17)

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
print(np.arange(1, 5), "\n") # => [1, 2, 3, 4] 짜리 array를 먼저 생성

Z = np.diag(np.arange(1, 5)) # => [1, 2, 3, 4]로 구성된 대각행렬 생성
print(Z, "\n")

Z = np.diag(np.arange(1, 5), k = -1) # k 는 대각선에서의 위치를 지정. 양수면 위로, 음수면 아래로
print(Z, "\n")

Z = np.diag(np.arange(1, 5), k = 1)
print(Z)

[1 2 3 4] 

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]] 

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]] 

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


In [ ]:
answer(18)

Z = np.diag(1+np.arange(4),k=-1)
print(Z)


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
Z = np.zeros((8, 8))
print(Z, "\n")

# numpy에서는 [start:end:step]으로 구성됨을 기억하자.
Z[1::2, ::2] = 1 # 짝수 번째 row는 첫 번째 column부터 2개씩 띄우면서 1로 채움
Z[::2, 1::2] = 1 # 홀수 번째 row는 두 번째 column부터 2개씩 띄우면서 1로 채움
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]] 

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
answer(19)

Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
Z = np.ones((6, 7, 8))

# 원하는 원소의 위치, (사이즈)
print(np.unravel_index(99, (6, 7, 8)))

(1, 5, 3)


In [ ]:
answer(20)

print(np.unravel_index(99,(6,7,8)))
