# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

In [ ]:
import os

os.chdir('/content/drive/MyDrive/numpy-100')

In [ ]:
!pip install mdutils

  Created wheel for mdutils: filename=mdutils-1.3.0-cp37-none-any.whl size=19449 sha256=5d436ac5ee85959bd7f1d1dcca5426dd7d755f4d568bcca9c82ba3d02c997e9f
  Stored in directory: /root/.cache/pip/wheels/af/fa/1c/7b13e92bdfc39eda5970b21a15f04f6a5158dea4e3f459854d
Successfully built mdutils


File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
A = np.arange(50).reshape(5, 10)
print("Original: ", A)

given_value = 11.8

print(A.flat[np.abs(A - given_value).argmin()])

Original:  [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
12


In [ ]:
answer(61)

Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)
결과가 (3, 3) 형태로 나와야됨

In [ ]:
A = np.arange(1, 4).reshape(1, 3)
print(A)

B = np.arange(5, 8).reshape(3, 1)
print(B)
#print(A.flatten())
#print(B.flatten())
#print(A.flatten()  B.flatten())

#it = np.nditer([A.flatten() B.flatten()])

#while not it.finished:
#    print(it[0])
#    it.iternext()


it = np.nditer([A,B, None])

for x,y,z in it:
    print(x, y, z)
    z = x + y
    print("Z:", z)
print(it.operands[2])
print(it.operands[0])
print(it.operands[1])


[[1 2 3]]
[[5]
 [6]
 [7]]
1 5 6
Z: 6
2 5 7
Z: 7
3 5 8
Z: 8
1 6 7
Z: 7
2 6 8
Z: 8
3 6 9
Z: 9
1 7 8
Z: 8
2 7 9
Z: 9
3 7 10
Z: 10
[[ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]]
[[1 2 3]]
[[5]
 [6]
 [7]]


In [ ]:
answer(62)

A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])


#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
answer(63)

class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)
벡터가 하나 주어졌다고 했을 때, 다른 벡터에 의해 주어진 index를 가지고 주어진 벡터의 각 요소에 1을 더해주는 방법은?


In [ ]:
A = np.ones(10)
B = np.random.randint(0, len(A), 20)

print(B)
np.add.at(A, B, 1)
print(A)

[1 4 5 7 1 4 1 0 3 2 3 9 5 2 2 4 6 3 1 6]
[2. 5. 4. 4. 4. 3. 3. 2. 1. 2.]


In [ ]:
answer(64)

# Author: Brett Olsen

Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
X = [1, 2, 3, 4, 5, 6]
I = [1, 3, 9, 3, 4, 1]
F = np.bincount(I, X) # count numbers in I, and weight is X. 
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [ ]:
answer(65)

# Author: Alan G Isaac

X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [ ]:
w, h = 15 , 15
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors, counts = np.unique(I.reshape(-1, 3), axis = 0, return_counts = True)
print(colors)
print(counts)

[[0 0 0]
 [0 0 1]
 [0 0 2]
 [0 0 3]
 [0 1 0]
 [0 1 1]
 [0 1 2]
 [0 1 3]
 [0 2 0]
 [0 2 1]
 [0 2 2]
 [0 2 3]
 [0 3 0]
 [0 3 1]
 [0 3 2]
 [0 3 3]
 [1 0 0]
 [1 0 1]
 [1 0 2]
 [1 0 3]
 [1 1 0]
 [1 1 1]
 [1 1 2]
 [1 1 3]
 [1 2 0]
 [1 2 1]
 [1 2 2]
 [1 2 3]
 [1 3 0]
 [1 3 1]
 [1 3 2]
 [1 3 3]
 [2 0 0]
 [2 0 2]
 [2 0 3]
 [2 1 0]
 [2 1 1]
 [2 1 2]
 [2 1 3]
 [2 2 0]
 [2 2 1]
 [2 2 2]
 [2 2 3]
 [2 3 0]
 [2 3 1]
 [2 3 2]
 [2 3 3]
 [3 0 0]
 [3 0 1]
 [3 0 2]
 [3 0 3]
 [3 1 0]
 [3 1 1]
 [3 1 2]
 [3 1 3]
 [3 2 2]
 [3 2 3]
 [3 3 0]
 [3 3 1]
 [3 3 2]
 [3 3 3]]
[6 3 6 2 1 4 3 4 2 2 3 4 2 2 3 5 5 7 2 2 2 2 4 9 6 4 6 3 5 4 3 1 3 3 4 5 3
 3 4 1 6 4 4 5 5 6 4 3 1 5 3 5 5 4 4 3 1 5 2 2 5]


In [ ]:
answer(66)

# Author: Fisher Wang

w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

# Faster version
# Author: Mark Setchell
# https://stackoverflow.com/a/59671950/2836621

w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

# View each pixel as a single 24-bit integer, rather than three 8-bit bytes
I24 = np.dot(I.astype(np.uint32),[1,256,65536])

# Count unique colours
n = len(np.unique(I24))
print(n)


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
A = np.random.randint(0,10,(3,4,3,4))
print(A)

print(A.sum(axis = (-2, -1)))
print(np.sum(A, axis = (-2, -1))) # same result?

[[[[9 4 6 2]
   [5 4 7 2]
   [7 1 0 9]]

  [[5 7 9 3]
   [4 8 5 1]
   [1 0 7 8]]

  [[3 7 2 8]
   [4 9 3 9]
   [8 9 7 2]]

  [[5 9 3 8]
   [0 3 5 7]
   [4 6 2 7]]]


 [[[7 8 1 7]
   [0 3 1 5]
   [3 6 4 6]]

  [[3 4 0 8]
   [9 7 5 0]
   [2 2 1 5]]

  [[2 0 8 0]
   [9 0 1 8]
   [8 1 4 8]]

  [[0 0 2 2]
   [5 3 8 9]
   [4 3 8 8]]]


 [[[5 8 7 5]
   [9 8 4 3]
   [6 3 7 2]]

  [[6 3 1 3]
   [8 6 7 1]
   [9 0 6 2]]

  [[6 0 1 9]
   [3 9 5 0]
   [5 8 6 2]]

  [[5 8 4 1]
   [4 5 7 6]
   [0 0 7 6]]]]
[[56 58 71 59]
 [51 46 49 52]
 [67 52 54 53]]
[[56 58 71 59]
 [51 46 49 52]
 [67 52 54 53]]


In [ ]:
answer(67)

A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)


In [ ]:
hint(67)

hint: sum(axis=(-2,-1))


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
D = np.array([1, 2, 3, 4, 5, 6, 5, 4, 4, 2])
S = np.array([0, 2, 3, 5, 0, 2, 1, 4, 6, 7]) # subset indices

D_sums = np.bincount(S, D) 
print(D_sums)

D_counts = np.bincount(S) # subset counts
print(D_counts)

D_means = D_sums / D_counts
print(D_means)

[6. 5. 8. 3. 4. 4. 4. 2.]
[2 1 2 1 1 1 1 1]
[3. 5. 4. 3. 4. 4. 4. 2.]


In [ ]:
answer(68)

# Author: Jaime Fernández del Río

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())


#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[1, 2, 1], [1, 2, 1], [1, 2, 1]])

print(np.diag(np.dot(A, B)))

[ 6 30 24]


In [ ]:
answer(69)

# Author: Mathieu Blondel

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
A = np.array([1, 2, 3, 4, 5])

B = np.zeros(len(A) * 4)
print(B)

B[::4] = A
print(B)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5. 0. 0. 0.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
A = np.arange(5*5*3).reshape(5, 5, 3)
print(A, A.shape)

B = 2 * np.ones((5, 5))
print(B[:, :, None].shape) # (5, 5, 1)

print("Those are equal?" , np.array_equal(B[:, :, None], np.expand_dims(B, axis = -1))) # 사실상 같음. 그냥 expand_dims를 쓰는게 낫지 않을까?

print(A * np.expand_dims(B, axis = - 1)) # 즉, (5,5)를 (5, 5, 1)로 만들어서 차원을 맞춰서 연산하게 만들어준 것

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]]

 [[45 46 47]
  [48 49 50]
  [51 52 53]
  [54 55 56]
  [57 58 59]]

 [[60 61 62]
  [63 64 65]
  [66 67 68]
  [69 70 71]
  [72 73 74]]] (5, 5, 3)
Those are equal? True
[[[  0.   2.   4.]
  [  6.   8.  10.]
  [ 12.  14.  16.]
  [ 18.  20.  22.]
  [ 24.  26.  28.]]

 [[ 30.  32.  34.]
  [ 36.  38.  40.]
  [ 42.  44.  46.]
  [ 48.  50.  52.]
  [ 54.  56.  58.]]

 [[ 60.  62.  64.]
  [ 66.  68.  70.]
  [ 72.  74.  76.]
  [ 78.  80.  82.]
  [ 84.  86.  88.]]

 [[ 90.  92.  94.]
  [ 96.  98. 100.]
  [102. 104. 106.]
  [108. 110. 112.]
  [114. 116. 118.]]

 [[120. 122. 124.]
  [126. 128. 130.]
  [132. 134. 136.]
  [138. 140. 142.]
  [144. 146. 148.]]]


In [ ]:
answer(71)

A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])


#### 72. How to swap two rows of an array? (★★★)

In [ ]:
A = np.arange(15).reshape(3, 5)
print(A)

A[[0, 1]] = A[[1, 0]]

print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]]


In [ ]:
# 두 개가 동일합니다.
print(A[[0, 1], :])
print(A[[0, 1]])

#즉, A[[0, 1]] 두 열로 구성된 submatrix를 만드는 것입니다.

[[5 6 7 8 9]
 [0 1 2 3 4]]
[[5 6 7 8 9]
 [0 1 2 3 4]]


In [ ]:
answer(72)

# Author: Eelco Hoogendoorn

A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [ ]:
# 이 문제는 문제를 이해 못했음 ㅠㅠ
faces = np.random.randint(0, 100, (10, 3))
print(faces)
F = np.roll(faces.repeat(2, axis = 1), -1, axis = 1) # face를 2번씩 반복시킨 다음, 가로 기준으로 가장 끝쪽부터 배열되도록 만들어줌
print(F)
F = F.reshape(len(F)*3, 2) # (30, 2)로 만들어줌
print(F)
F = np.sort(F, axis = 1) # 가로 기준으로 오름차순 배열
print(F)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[[28 92 44]
 [61 14 52]
 [77 95 71]
 [ 5 20 60]
 [74 47 69]
 [47 34 81]
 [48 13 64]
 [77 85 42]
 [91 82 96]
 [ 1 47 72]]
[[28 92 92 44 44 28]
 [61 14 14 52 52 61]
 [77 95 95 71 71 77]
 [ 5 20 20 60 60  5]
 [74 47 47 69 69 74]
 [47 34 34 81 81 47]
 [48 13 13 64 64 48]
 [77 85 85 42 42 77]
 [91 82 82 96 96 91]
 [ 1 47 47 72 72  1]]
[[28 92]
 [92 44]
 [44 28]
 [61 14]
 [14 52]
 [52 61]
 [77 95]
 [95 71]
 [71 77]
 [ 5 20]
 [20 60]
 [60  5]
 [74 47]
 [47 69]
 [69 74]
 [47 34]
 [34 81]
 [81 47]
 [48 13]
 [13 64]
 [64 48]
 [77 85]
 [85 42]
 [42 77]
 [91 82]
 [82 96]
 [96 91]
 [ 1 47]
 [47 72]
 [72  1]]
[[28 92]
 [44 92]
 [28 44]
 [14 61]
 [14 52]
 [52 61]
 [77 95]
 [71 95]
 [71 77]
 [ 5 20]
 [20 60]
 [ 5 60]
 [47 74]
 [47 69]
 [69 74]
 [34 47]
 [34 81]
 [47 81]
 [13 48]
 [13 64]
 [48 64]
 [77 85]
 [42 85]
 [42 77]
 [82 91]
 [82 96]
 [91 96]
 [ 1 47]
 [47 72]
 [ 1 72]]
[( 1, 47) ( 1, 72) ( 5, 20) ( 5, 60) (13, 48) (13, 64) (14, 52) (14, 61)
 (20, 60) (28, 44) (28, 92) (34, 47) (34, 81) (42, 77

In [ ]:
answer(73)

# Author: Nicolas P. Rougier

faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
A = np.array([1, 3, 4, 2, 0, 5, 3, 1, 6, 2, 4])
A = np.sort(A)
print("Original array: ", A)
C = np.bincount(A)
print("bincount: ", C)

print(np.repeat(np.arange(len(C)), C[::1]))

Original array:  [0 1 1 2 2 3 3 4 4 5 6]
bincount:  [1 2 2 2 2 1 1]
[0 1 1 2 2 3 3 4 4 5 6]


In [ ]:
answer(74)

# Author: Jaime Fernández del Río

C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)


In [ ]:
hint(74)

hint: np.repeat


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
A = np.arange(10)

C = np.cumsum(A)
print(C)

C[3:] = C[3:] - C[:-3]
print(C)
print(C[2:] / 3) # 3개 당 평균을 나타낸 것인듯

[ 0  1  3  6 10 15 21 28 36 45]
[ 0  1  3  6  9 12 15 18 21 24]
[1. 2. 3. 4. 5. 6. 7. 8.]


In [ ]:
answer(75)

# Author: Jaime Fernández del Río

def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))


In [ ]:
hint(75)

hint: np.cumsum


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:
from numpy.lib import stride_tricks

# stride가 정확히 뭔지 알기가 어렵다.

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
answer(76)

# Author: Joe Kington / Erik Rigtorp
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [ ]:
print(np.logical_not(False))

A = np.arange(10)
np.negative(A, out = A)
print(A)

True
[ 0 -1 -2 -3 -4 -5 -6 -7 -8 -9]


In [ ]:
answer(77)

# Author: Nathaniel J. Smith

Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [ ]:
answer(78)

def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [ ]:
answer(79)

# Author: Italmassov Kuanysh

# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [ ]:
answer(80)

# Author: Nicolas Rougier

Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)


In [ ]:
Z = np.random.randint(0,10, (10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill # (5, 5) 짜리 0으로 채워진 것
P  = np.array(list(position)).astype(int) # [1, 1]
Rs = np.array(list(R.shape)).astype(int) # [5, 5]
Zs = np.array(list(Z.shape)).astype(int) # [10, 10]

# 0으로 채워진 R을 기준으로 시작점과 도착점을 지정
R_start = np.zeros((len(shape),)).astype(int) # [0, 0]
R_stop  = np.array(list(shape)).astype(int) # [5, 5]

# position인 (1, 1)을 기준으로, 시작점 (-1, -1)과 도착점 (4, 4)을 잡음
Z_start = (P-Rs//2) # [-1, -1], 위치 (1, 1) 에서 shape (5, 5)를 만들기 위해 x축과 y축으로 2씩 이동하게 됨
Z_stop  = (P+Rs//2)+Rs%2 # [4, 4], [-1, -1]로부터 shape 만큼 5 5 씩 더해서 최종 지점을 잡음

# 0으로 채워진 R을 기준으로 어느 지점부터 채워야할지를 지정
# Z_start가 음수라면, 그만큼 0으로 채워야 하는 것이므로, 오히려 이를 빼서 실제로 채워야 하는 지점을 잡아줌
R_start = (R_start - np.minimum(Z_start,0)).tolist() # [1, 1]

# np.maximum으로 0보다 작으면 0으로 만들어줌. 이는 Z에서의 시작점 위치를 의미
Z_start = (np.maximum(Z_start,0)).tolist() # [0, 0]

# Z_stop이 실제 Zs인 10을 넘는지 확인하고, 넘지 않으면 R_stop을 그대로 사용
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist() # [5, 5]

# Z_stop이 Zs를 넘지 않으므로, 그대로 사용
Z_stop = (np.minimum(Z_stop,Zs)).tolist() # [4, 4]


r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[6 8 0 3 5 6 6 0 7 8]
 [7 4 6 0 6 9 3 1 7 6]
 [7 3 2 3 2 3 1 2 4 0]
 [3 3 6 2 4 8 4 6 1 8]
 [1 1 4 8 2 9 0 5 4 0]
 [6 6 8 5 2 1 7 6 3 3]
 [7 2 2 7 3 7 7 0 5 4]
 [7 2 4 1 7 3 6 5 6 7]
 [5 1 8 0 2 0 5 7 2 4]
 [7 9 6 8 6 2 3 6 7 2]]
[[0 0 0 0 0]
 [0 6 8 0 3]
 [0 7 4 6 0]
 [0 7 3 2 3]
 [0 3 3 6 2]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:35: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


In [ ]:
hint(80)

hint: minimum maximum
