# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

In [ ]:
import os

os.chdir('/content/drive/MyDrive/numpy-100')

In [ ]:
!pip install mdutils

  Created wheel for mdutils: filename=mdutils-1.3.0-cp37-none-any.whl size=19449 sha256=26ea339db828c860fdf02182aadd568224703c8d7abaae4bee4a37590cd88809
  Stored in directory: /root/.cache/pip/wheels/af/fa/1c/7b13e92bdfc39eda5970b21a15f04f6a5158dea4e3f459854d
Successfully built mdutils


File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
a = np.array([[0, 1], [1, 0]])

# np.tile은 array를 반복해서 만드는 함수
print(np.tile(a, (4, 4)))


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
answer(21)

Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
Z = np.random.random((5, 5))
Z = (Z - np.mean(Z)) / (np.std(Z))
print(Z)

[[-0.83731691  1.64392294  0.50791016 -0.28586433  0.03090355]
 [-1.33027411  0.60376178 -0.67801567  1.49087304  0.11640778]
 [-1.2531939   0.57947362 -1.70722552  1.4102641  -0.07600729]
 [-1.2059934   0.52851473 -0.19305176  1.5757194   1.00184877]
 [ 0.98476446 -0.60701467 -0.86145293 -1.50589207  0.06693824]]


In [ ]:
answer(22)

Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
# https://stackoverflow.com/questions/621290/what-is-the-difference-between-signed-and-unsigned-variables
# signed byte => -128 ~ 127, np.byte
# unsigned bytes => 0 ~ 255를 표현, np.ubyte


color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [ ]:
answer(23)

color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
A = np.ones((5, 3))
B = np.ones((3, 2))

print(np.dot(A, B))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [ ]:
answer(24)

Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
Z = np.arange(11)

Z[(3 < Z[:]) & (Z[:] < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [ ]:
answer(25)

# Author: Evgeni Burovski

Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5), -1)) # 9 => 10 + (-1)인 것
from numpy import *
print(sum(range(5), -1)) # 10 => np.sum(range(5), axis = -1)이라서 답이 10

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
import numpy as np
Z = np.array([3], dtype = np.int8)

print(Z ** Z)
print( 2 << Z >> 2) # x << y이면 x * 2**y이고, x >> y이면 x / 2**y이다.
print( Z<- Z) # Z < -Z라고 읽혀짐
print(1j * Z) 
print(Z/1/1)
print(Z<Z>Z)

27
4
False
3j
3.0
False


#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0)) # nan
print(np.array(0) // np.array(0)) # 0
print(np.array([np.nan]).astype(int).astype(float)) # 매우 작은 값

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
Z = np.random.uniform(-10,+10,10)
print(Z) # 원래 값
print(np.copysign(np.ceil(np.abs(Z)), Z)) # 정답값

print(np.abs(Z)) # 절대값
print(np.ceil(np.abs(Z))) # 올림
# np.copysign => 해당 값을 기존의 Z의 부호대로 바꿔줌

[-1.05382292  1.77554066 -5.84296794  2.64447635 -4.94530498 -8.04941648
  9.52946393  7.71022324  1.21113436 -3.66909642]
[-2.  2. -6.  3. -5. -9. 10.  8.  2. -4.]
[1.05382292 1.77554066 5.84296794 2.64447635 4.94530498 8.04941648
 9.52946393 7.71022324 1.21113436 3.66909642]
[ 2.  2.  6.  3.  5.  9. 10.  8.  2.  4.]


In [ ]:
answer(29)

# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
A = np.array([1, 2, 3, 4, 5])
B = np.array([3, 4, 5, 6])

print(np.intersect1d(A, B))

[3 4 5]


In [ ]:
answer(30)

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

In [ ]:
answer(31)

# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
print(np.sqrt(-1)) # 허수이므로 nan이 출력됨
print(np.emath.sqrt(-1)) # 허수 형태로 1j 출력. 정교한 숫자 표현을 제공하는듯

nan
1j


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
today = np.datetime64('today') # 오늘 날짜 생성
print(today)
yesterday = np.datetime64('today') - np.timedelta64(1) # timedelta를 이용해서 날짜 빼기
print(yesterday)
tomorrow = np.datetime64('today') + np.timedelta64(1) # timedelta를 이용해서 날짜 더하기
print(tomorrow)

2021-04-07
2021-04-06
2021-04-08


In [ ]:
hint(33)

hint: np.datetime64, np.timedelta64


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
print(np.arange('2016-07', '2016-08', dtype = 'datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [ ]:
answer(34)

Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
(별도로 변수에 copy하지 않고 값을 저장할 수 있는가(A, B에))

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
print(A, B)

np.add(A, B, out = B)
print(A, B)

np.divide(A, 2, out = A)
print(A, B)

np.negative(A, out = A)
print(A, B)

np.multiply(A, B, out = A)
print(A, B)


[1. 1. 1.] [2. 2. 2.]
[1. 1. 1.] [3. 3. 3.]
[0.5 0.5 0.5] [3. 3. 3.]
[-0.5 -0.5 -0.5] [3. 3. 3.]
[-1.5 -1.5 -1.5] [3. 3. 3.]


In [ ]:
answer(35)

A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


In [ ]:
hint(35)

hint: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=)


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
A = np.random.uniform(0 ,10, 10)
print(A)

print(A - A%1) # 원래 값에서 1로 나누었을 때의 나머지를 빼서 소수 부분을 제외
print(A // 1) # 1로 나누었을 때의 몫
print(np.floor(A)) # 내림
print(A.astype(int)) # int로 자료형 변환
print(np.trunc(A)) # 
#print(np.int32(A)) # 이런건줄 알았다 ~
#print(np.int16(A))
#print(np.int8(A))
#print(np.int64(A))

[7.69054299 4.0368992  3.32210217 9.37704411 2.10349466 2.52231232
 8.30386504 6.27977919 1.32416962 9.79150227]
[7. 4. 3. 9. 2. 2. 8. 6. 1. 9.]
[7. 4. 3. 9. 2. 2. 8. 6. 1. 9.]
[7. 4. 3. 9. 2. 2. 8. 6. 1. 9.]
[7 4 3 9 2 2 8 6 1 9]
[7. 4. 3. 9. 2. 2. 8. 6. 1. 9.]


In [ ]:
answer(36)

Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
A = np.zeros((5, 5))
print(A, "\n")

A[:, :] = np.arange(5) # 이렇게도 구현 가능
#A += np.arange(5) # 답안에 나온 코드
print(A)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [ ]:
answer(37)

Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def generate():
    for x in range(10):
        yield x

a = np.fromiter(generate(), dtype = int)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
answer(38)

def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
A = np.array(np.linspace(start = 0, stop = 1, num = 11, endpoint = False))[1:]
print(A)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [ ]:
answer(39)

Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
A = np.random.random(10)
A.sort()
print(A)

[0.13343222 0.16382466 0.27203988 0.27358989 0.41596526 0.43518639
 0.51199027 0.64378609 0.90144345 0.97243962]


In [ ]:
answer(40)

Z = np.random.random(10)
Z.sort()
print(Z)
