# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

In [ ]:
import os

os.chdir('/content/drive/MyDrive/numpy-100')

In [ ]:
!pip install mdutils

  Created wheel for mdutils: filename=mdutils-1.3.0-cp37-none-any.whl size=19449 sha256=26ea339db828c860fdf02182aadd568224703c8d7abaae4bee4a37590cd88809
  Stored in directory: /root/.cache/pip/wheels/af/fa/1c/7b13e92bdfc39eda5970b21a15f04f6a5158dea4e3f459854d
Successfully built mdutils


File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
Z = np.arange(10)

print(np.add.reduce(Z))

45


In [ ]:
hint(41)

hint: np.add.reduce


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
A = np.array([1, 2, 3, 4])
B = np.array([1, 2, 3, 4])

print(np.equal(A, B)) # 요소 별로 같은지 확인
print(np.array_equal(A, B)) # 완전히 다 같은지 확인, shape / element 모두 같아야함.

C = np.array([1, 2, 3, 4])
D = np.array([1, 2, 3, 5])

print(np.equal(C, D))
print(np.array_equal(C, D))

[ True  True  True  True]
True
[ True  True  True False]
False
False


In [ ]:
answer(42)

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
A = np.arange(10)
print(A)
print(A.flags.writeable)

# Make immutable
A.flags.writeable = False

print(A)
print(A.flags.writeable)

A[0] = 2 # make ValueError

[0 1 2 3 4 5 6 7 8 9]
True
[0 1 2 3 4 5 6 7 8 9]
False


ValueError: ignored

In [ ]:
answer(43)

Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
A = np.random.random((10, 2))
print(A)

x, y = A[:, 0], A[:, 1]
r = np.sqrt(x**2 + y**2)
phi = np.arctan2(y, x) # tan = y / x 이므로, arctan을 이용해서 각도를 구한다. np.arctan2은 arctangent of x1 / x2이며, 출력 범위가 [-pi , pi]이다.
print(r)
print(phi)

[[0.77718467 0.10761439]
 [0.7871605  0.07291056]
 [0.66487176 0.17515174]
 [0.31934029 0.32167685]
 [0.49576433 0.76835583]
 [0.10692424 0.75043755]
 [0.45761413 0.01872655]
 [0.48222247 0.68282023]
 [0.98596825 0.68630734]
 [0.99528915 0.03587467]]
[0.78459982 0.79052995 0.68755551 0.45327058 0.91441399 0.7580167
 0.45799713 0.8359318  1.20131227 0.99593548]
[0.13759204 0.09236124 0.25758461 0.78904323 0.99778342 1.42926641
 0.04089932 0.95590692 0.60808653 0.03602888]


In [ ]:
answer(44)

Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
A = np.random.random(10)
A[A.argmax()] = 0 
print(A)

[0.24053676 0.30389194 0.19146807 0.50838178 0.31375528 0.12193417
 0.73050676 0.         0.3832864  0.13906292]


In [ ]:
answer(45)

Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
Z = np.zeros((5, 5), [('x', float), ('y', float)]) # Custom dtype 가능

print(Z)

Z['x'], Z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))

print(Z)

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]
[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [ ]:
answer(46)

Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [ ]:
X = np.array([1, 2, 3, 4, 5])
Y = np.array([6, 7, 8, 9, 10])

result = np.subtract.outer(X, Y) # (xi - yj)
print(result)

result = 1 / result
print(result)

[[-5 -6 -7 -8 -9]
 [-4 -5 -6 -7 -8]
 [-3 -4 -5 -6 -7]
 [-2 -3 -4 -5 -6]
 [-1 -2 -3 -4 -5]]
[[-0.2        -0.16666667 -0.14285714 -0.125      -0.11111111]
 [-0.25       -0.2        -0.16666667 -0.14285714 -0.125     ]
 [-0.33333333 -0.25       -0.2        -0.16666667 -0.14285714]
 [-0.5        -0.33333333 -0.25       -0.2        -0.16666667]
 [-1.         -0.5        -0.33333333 -0.25       -0.2       ]]


In [ ]:
answer(47)

# Author: Evgeni Burovski

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
# int info
print(np.iinfo(np.int16).min)
print(np.iinfo(np.int32).min)

# float info
print(np.finfo(np.float16).min)
print(np.finfo(np.float16).max)
print(np.finfo(np.float16).eps) # smallest representable number such that 1.0 + eps != 1.0

-32768
-2147483648
-65500.0
65500.0
0.000977


In [ ]:
answer(48)

for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)


#### 49. How to print all the values of an array? (★★☆)

In [ ]:
import sys
print("sys.maxsize: ", sys.maxsize)
np.set_printoptions(threshold = sys.maxsize) # Document에 따르면 이렇게 표현하는게 맞는듯.
Z = np.random.random(10)
print(Z)

sys.maxsize:  9223372036854775807
[0.8789165815452501  0.8951990165438026  0.628274307134482
 0.5035553602934985  0.510261791673288   0.3362004488759789
 0.27736050898163245 0.8742275295966666  0.6120004671155443
 0.37121841622323326]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
given_scalar = np.array([3])
A = np.arange(10)

index = (np.abs(given_scalar - A)).argmin()
print(A[index])

3


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
A = np.zeros(10, [('position', [('x', float),
                                ('y', float)]),
                  ('color',    [('r', float),
                                ('g', float),
                                ('b', float)])])

print(A)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [ ]:
answer(51)

Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
각 좌표간의 거리를 matrix 형태로 구하라.

In [ ]:
Z = np.random.random((5, 2))
print(Z[:, 0].shape) # 하나의 column만 빼면 원래는 1차원이 됨
x, y = np.atleast_2d(Z[:, 0], Z[:, 1]) # np.atleast_2d를 적용하면 이를 2차원으로 만들어줌

print(x)
print(x.T)
print(x-x.T)

Dis = np.sqrt( (x-x.T)**2 + (y-y.T)**2 )
print(Dis)

(5,)
[[0.8168 0.7256 0.1798 0.5083 0.5491]]
[[0.8168]
 [0.7256]
 [0.1798]
 [0.5083]
 [0.5491]]
[[ 0.     -0.0912 -0.637  -0.3085 -0.2677]
 [ 0.0912  0.     -0.5457 -0.2173 -0.1765]
 [ 0.637   0.5457  0.      0.3284  0.3693]
 [ 0.3085  0.2173 -0.3284  0.      0.0408]
 [ 0.2677  0.1765 -0.3693 -0.0408  0.    ]]
[[0.     0.5633 0.8524 0.7561 0.7319]
 [0.5633 0.     0.5458 0.2556 0.2165]
 [0.8524 0.5458 0.     0.351  0.3867]
 [0.7561 0.2556 0.351  0.     0.0418]
 [0.7319 0.2165 0.3867 0.0418 0.    ]]


In [ ]:
answer(52)

Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?
(In-place means that you should update the original string rather than creating a new one.)

In [ ]:
import numpy as np
x = np.arange(10, dtype=np.float32) 
print(x, x.dtype)
y = x.view(np.int32)
print(y, y.dtype)
y[:] = x

print(y, y.dtype)
print(x, x.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float32
[         0 1065353216 1073741824 1077936128 1082130432 1084227584
 1086324736 1088421888 1090519040 1091567616] int32
[0 1 2 3 4 5 6 7 8 9] int32
[0.0e+00 1.4e-45 2.8e-45 4.2e-45 5.6e-45 7.0e-45 8.4e-45 9.8e-45 1.1e-44
 1.3e-44] float32


In [ ]:
# 이렇게도 가능
X = np.arange(10, dtype = np.float32)
print(X)
X = X.astype(np.int32, copy = False)
print(X)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
answer(53)

# Thanks Vikas (https://stackoverflow.com/a/10622758/5989906)
# & unutbu (https://stackoverflow.com/a/4396247/5989906)
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')

Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


In [ ]:
answer(54)

from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)


In [ ]:
hint(54)

hint: np.genfromtxt


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
A = np.ones((3, 4))
print(A)

for index, value in np.ndenumerate(A): # 실제 enumerate와 거의 동일한 형식으로 작동하는 함수
    print(index, value)

print("\n")

for index in np.ndindex(A.shape): # ndindex는 특정한 shape를 입력 받아서, 이를 이용해 N-dimensional iterator를 만들어주는 것.
    print(index, A[index])

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(0, 0) 1.0
(0, 1) 1.0
(0, 2) 1.0
(0, 3) 1.0
(1, 0) 1.0
(1, 1) 1.0
(1, 2) 1.0
(1, 3) 1.0
(2, 0) 1.0
(2, 1) 1.0
(2, 2) 1.0
(2, 3) 1.0


(0, 0) 1.0
(0, 1) 1.0
(0, 2) 1.0
(0, 3) 1.0
(1, 0) 1.0
(1, 1) 1.0
(1, 2) 1.0
(1, 3) 1.0
(2, 0) 1.0
(2, 1) 1.0
(2, 2) 1.0
(2, 3) 1.0


In [ ]:
answer(55)

Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])


#### 56. Generate a generic 2D Gaussian-like array (★★☆)
x, y 기준 (-1, 1)인 10x10 도트를 찍고, 각 좌표의 원점과의 거리를 계산한 다음 이를 Gaussian처럼 값을 계산.

In [ ]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X + Y*Y)
print(D.shape)
print(X.shape)
sigma, mu = 1.0, 0.0
G = np.exp(-((D - mu)**2 / (2.0 * sigma ** 2)))
print(G)

(10, 10)
(10, 10)
[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444

In [ ]:
answer(56)

X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)


#### 57. How to randomly place p elements in a 2D array? (★★☆)
임의로 p개의 element를 다른 값으로 바꾸는 방법

In [ ]:
A = np.random.random((5, 5))
print("original: ", A)

np.put(A, np.random.choice(range(A.size), 3, replace = False), 1) # replace는 복원 추출인지 아닌지를 결정
print("After:", A)

original:  [[0.26442904 0.629319   0.42153862 0.1962841  0.38880068]
 [0.68799403 0.19027833 0.62373937 0.29600401 0.0318608 ]
 [0.63747466 0.70719748 0.80725175 0.93262577 0.36877577]
 [0.64134861 0.36743992 0.12258669 0.58231963 0.70835228]
 [0.71039439 0.01652439 0.79897617 0.03904677 0.71291035]]
[24 21 23]
After: [[0.26442904 1.         0.42153862 0.1962841  0.38880068]
 [0.68799403 0.19027833 0.62373937 0.29600401 0.0318608 ]
 [0.63747466 0.70719748 0.80725175 0.93262577 0.36877577]
 [1.         1.         0.12258669 0.58231963 0.70835228]
 [0.71039439 0.01652439 0.79897617 0.03904677 0.71291035]]


In [ ]:
answer(57)

# Author: Divakar

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
A = np.arange(50).reshape(5, 10)
print(A)

print((A.T - A.mean(axis = 1)).T) # 내가 만든 답

Y = A - A.mean(axis=1, keepdims = True) # 답지에 나온 답
print(Y)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[[-4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5]
 [-4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5]
 [-4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5]
 [-4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5]
 [-4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5]]
[[-4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5]
 [-4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5]
 [-4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5]
 [-4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5]
 [-4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5]]


#### 59. How to sort an array by the nth column? (★★☆)
n번째 column 기준으로 array를 sort할 수 있는가?

In [ ]:
A = np.random.random((5, 3))
print(A)

print(A[:, 1].argsort())
print(A[A[:, 1].argsort()]) # 두 번째 column 기준으로 sort

[[0.93600502 0.00197711 0.47737051]
 [0.78220841 0.12779602 0.07684968]
 [0.23260538 0.97894505 0.45833067]
 [0.90173408 0.36441637 0.27536279]
 [0.21787443 0.15997079 0.86732299]]
[0 1 4 3 2]
[[0.93600502 0.00197711 0.47737051]
 [0.78220841 0.12779602 0.07684968]
 [0.21787443 0.15997079 0.86732299]
 [0.90173408 0.36441637 0.27536279]
 [0.23260538 0.97894505 0.45833067]]


In [ ]:
answer(59)

# Author: Steve Tjoa

Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
A = np.random.random((3, 4))
print(A.any(axis = 0)) # any(axis = 0)을 이용하면 해당 column에 값이 있는지 없는지 판단해줌
print((~A.any(axis = 0))) # ~ 는 반대로 값이 나오게 만들어줌

[ True  True  True  True]
[False False False False]


In [ ]:
answer(60)

# Author: Warren Weckesser

Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())
